In [5]:
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from matplotlib import pyplot as plt
from matplotlib import colors as mcolors
from sklearn.metrics import roc_curve
from scipy import interpolate

In [6]:
os.chdir(r'/home/manhducnmd/pp_dijet/Results_full')


In [3]:
mean_results = np.load('cwola_mean_id10.npy')
std_results = np.load('cwola_std_id10.npy')


In [10]:
print(mean_results, std_results)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
x = np.array([50, 100, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1100, 1200])
mean_results = np.zeros((np.shape(x)[0],3))
std_results = np.ones((np.shape(x)[0],3))
sig_before = np.sqrt(2*((x+25000)*np.log(x/25000 + 1) - x))
                     
sig_after_1 = np.sqrt(2*((x*mean_results[:,0]+25000*0.001)*np.log(x*mean_results[:, 0]/(25000*0.001) + 1)
                         -x*mean_results[:,0]))
sig_after_2 = np.sqrt(2*((x*mean_results[:,1]+25000*0.01)*np.log(x*mean_results[:, 1]/(25000*0.01) + 1)
                         -x*mean_results[:,1]))
sig_after_3 = np.sqrt(2*((x*mean_results[:,2]+25000*0.01)*np.log(x*mean_results[:, 2]/(25000*0.01) + 1)
                         -x*mean_results[:,2]))


                     
                    
                      
                      

In [11]:
from uncertainties import unumpy
array = unumpy([mean_results, std_results])

TypeError: 'module' object is not callable